### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by qtgiebel** [mad-ent-java-s22/indie-project#3]
# Design/Code Review 1

### Reviewer: Quinn Giebel

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person| Accurately desribes the project but could be more verbose. The problem statment seems to include elements of the solution. You might consider either exclusivly stating the problem, or removing the Solution as a subsection and presenting it all together. That being said, the Solution section is quite good as a description of the project. |
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens | Navigation is clean and simple. Styling it with Bootstrap is a good choice, especially in the absence of a dedicated UI/UX designer. Your values and form fields are laid out in an easy to follow hierarchy. I did notice that while the tags were visible on the homepage design they were not present in the article design. |
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>| Everything in the model you have does appear in the design docs, and you have not one, but three one to many relationships. Your database design is quite good with special kudos for using a bridge table to implement the many-to-many relationship. It does appear that the one-to-many user-tag relationship has not been implemented. |
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverage. | Your project structure is sound, and the gitignore is present. Some of the methods in your GenericDao are entity specific, e.g. getByUser; consider creating a subclass for the Post entity to implement this method and similar methods for other entities. All system prints and stacktraces have been removed, and the test for the generic dao appears comprehensive. |

**Comment by pawaitemadisoncollege** [comment]
Heads up that some print statements may have snuck in here since review time. https://github.com/mad-ent-java-s22/indie-project/search?q=print

**Comment by davidtcalabrese** [comment]
Thanks for the review Quinn
