### ISSUE TITLE
Checkpoint # 2

### ISSUE THREAD

**Issue by davidtcalabrese** [mad-ent-java-s22/indie-project#6]
@pawaitemadisoncollege indie project ready for checkpoint 2

- [x] Database designed and created
- [x] at least one DAO with full CRUD (create, read, update, delete) implemented with Hibernate
- [x] DAO is fully unit tested
- [x] Log4J is implemented (no System.out.printlns)

[Otter](http://blog-env.eba-by2p9nya.us-east-2.elasticbeanstalk.com/)
* still not able to get sign up and log in to work through Cognito. I can see the users I create in my user pools but when I try to sign in I'm taken to an error page.

**Comment by pawaitemadisoncollege** [comment]
Hi @davidtcalabrese 

I started poking around a bit to see what I could discern related to not being able to sign up a user on the deployed app.  Here is what I foundApplication home page with http works: http://blog-env.eba-by2p9nya.us-east-2.elasticbeanstalk.com

Application home page accessed through https does not work: https://blog-env.eba-by2p9nya.us-east-2.elasticbeanstalk.com

After signing in: https://blog-env.eba-by2p9nya.us-east-2.elasticbeanstalk.com/auth?code=a38c75dd-548f-48f2-8310-821196ede0d3 was not found by the server.

However http://blog-env.eba-by2p9nya.us-east-2.elasticbeanstalk.com/auth?code=e16826d0-ee00-447f-ae02-9e9fe144ef89, was found and the auth code was clearly running as there was a Base 64 error there.

**Comment by pawaitemadisoncollege** [comment]
Checkpoint 2 review: You are well ahead of the checkpoint targets. Once that https business is resolved on AWS that'll cover checkpoint 3 as well. Great work, @davidtcalabrese!

DB Design: Very solid design. Weekly reflections (and GitHub history) show consistent progress and careful thought around the project and your process.  Generic dao implemented, all three key tables/entities unit tested. Project is in an excellent position!

- [ ] Does the user table need that password column? 

- [ ] This may be a good time to review the project plan, check completed items off, move incomplete items forward, and consider whether any additional tasks are needed.

**Comment by davidtcalabrese** [comment]
Thank you for looking into my https problem and the review. 

I am adding the following To Dos:

- [ ] remove password column from user table
- [ ] revisit project plan
  - [ ] check off completed items
  - [ ] write tasks for next few weeks
