### ISSUE TITLE
Fix many to many relationship

### ISSUE THREAD

**Issue by davidtcalabrese** [mad-ent-java-s22/indie-project#7]
Something seems to broken with my Many to Many relationship between Post and Tag. I thought I had fixed the issue earlier but now I'm running into problems. When I insert blog data with SQL, I can click on a tag on the app and it will bring up all of the posts tagged with that tag. But when I create a post on the app and tag it, when I click on that tag it only brings up that single post. 

I did some digging and found a discrepancy between the ERDs generated from DB data and the Java entities. 

The database ERD looks correct:
![image](https://user-images.githubusercontent.com/69607423/159264005-34df3a54-9f6a-4d13-b5c6-a25b3f690fb8.png)

The ERD generated with IntelliJ's persistence tool is incorrect:
![image](https://user-images.githubusercontent.com/69607423/159264136-0fb9d8e4-75fb-44ed-8996-34264bc87019.png)

There should not be a direct relationship b/w Tag and Post entities, it should be going through the PostTag bridging entity. Here is the Entity ERD again with the connection sources superimposed on the connecting lines:
![image](https://user-images.githubusercontent.com/69607423/159264547-fb23c1de-8e7e-4cc2-94c1-99ca3681e1b2.png)

I think I know what the problem is. I should not have a `Set<Tag> tags` in the `Post` class and I should not have a `Set<Post> posts` in the `Tag` class. Instead, I think should have a `Set<PostTag> postTags` in both classes. 

Here's what the code looks like now. 
#### Tag.java
```java
@ManyToMany(mappedBy = "tags", fetch = "FetchType.EAGER)
private Set<Post> posts = new HashSet<>();
````

#### Post.java
```java
@ManyToMany(cascade = {
        CascadeType.PERSIST,
        CascadeType.MERGE
},
        fetch = FetchType.EAGER)
@JoinTable(name = "post_tag",
    joinColumns = { @JoinColumn(name = "post_id") },
    inverseJoinColumns = { @JoinColumn(name = "tag_id") }
)
private Set<Tag> tags = new HashSet<>();
```

And it should be:
#### Tag.java
```java
@ManyToMany(mappedBy = "tags", fetch = "FetchType.EAGER)
private Set<PostTag> postTags = new HashSet<>();
````

#### Post.java
```java
@ManyToMany(cascade = {
        CascadeType.PERSIST,
        CascadeType.MERGE
},
        fetch = FetchType.EAGER)
@JoinTable(name = "post_tag",
    joinColumns = { @JoinColumn(name = "post_id") },
    inverseJoinColumns = { @JoinColumn(name = "tag_id") }
)
private Set<PostTag> postTags = new HashSet<>();
```

I'm hoping the Hibernate annotations are still correct. I feel like I probably will have to make some other changes too, but I'm not sure what those will be yet.

**Comment by pawaitemadisoncollege** [comment]
Hi David, I thought this had been working previously as well... are there unit tests that cover this scenario? If so, do they still pass? 

I'm curious if the hibernate facet got turned on accidentally in IntelliJ and it is "taking over"? I had thought if the bridging table didn't have any extra columns, it wasn't necessary to have it included as an entity... though it certainly wouldn't be wrong to include it.

**Comment by davidtcalabrese** [comment]
Good point @pawaitemadisoncollege 

My proposed solution to this issue is no good. I shouldn't need the PostTag entity at all. I checked and there was not a Hibernate facet in IntelliJ's Project Structure setting. Something else must be going on to cause that Tag - Post relationship. I will do some digging in the Hibernate config file and everywhere else too. Thanks for responding so quick.
